CREATE TABLE device_types (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, category VARCHAR(50) NOT NULL, protocol VARCHAR(50) NOT NULL, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE devices (id SERIAL PRIMARY KEY, service_tag VARCHAR(20) NOT NULL, device_name VARCHAR(200), device_type_id INTEGER REFERENCES device_types(id), model VARCHAR(100) NOT NULL, ip_address INET NOT NULL, firmware_version VARCHAR(50), health_status VARCHAR(20) DEFAULT 'OK', power_state VARCHAR(20) DEFAULT 'On', ome_device_id INTEGER, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE device_inventory (id SERIAL PRIMARY KEY, device_id INTEGER NOT NULL REFERENCES devices(id), component_type VARCHAR(50) NOT NULL, component_name VARCHAR(200), manufacturer VARCHAR(100), model VARCHAR(200), serial_number VARCHAR(100), capacity VARCHAR(50), status VARCHAR(20) DEFAULT 'OK', created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE groups (id SERIAL PRIMARY KEY, name VARCHAR(200) NOT NULL, description TEXT, parent_group_id INTEGER REFERENCES groups(id), group_type VARCHAR(50) DEFAULT 'Static', created_by VARCHAR(100), created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE group_memberships (id SERIAL PRIMARY KEY, group_id INTEGER NOT NULL REFERENCES groups(id), device_id INTEGER NOT NULL REFERENCES devices(id), added_at TIMESTAMP DEFAULT NOW(), UNIQUE(group_id, device_id));
CREATE TABLE alert_categories (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, subcategories JSONB);
CREATE TABLE alerts (id SERIAL PRIMARY KEY, device_id INTEGER REFERENCES devices(id), alert_category_id INTEGER REFERENCES alert_categories(id), severity VARCHAR(20) NOT NULL, message TEXT NOT NULL, message_id VARCHAR(50), source VARCHAR(100), subcategory VARCHAR(100), acknowledged BOOLEAN DEFAULT false, alert_time TIMESTAMP NOT NULL DEFAULT NOW(), created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE device_health (id SERIAL PRIMARY KEY, device_id INTEGER NOT NULL REFERENCES devices(id), overall_health VARCHAR(20) NOT NULL, cpu_health VARCHAR(20), memory_health VARCHAR(20), storage_health VARCHAR(20), power_health VARCHAR(20), cpu_usage_percent NUMERIC(5,2), memory_usage_percent NUMERIC(5,2), system_temp_celsius NUMERIC(5,1), power_consumed_watts INTEGER, collected_at TIMESTAMP NOT NULL DEFAULT NOW());
CREATE TABLE firmware_catalog (id SERIAL PRIMARY KEY, name VARCHAR(200) NOT NULL, version VARCHAR(50) NOT NULL, component_type VARCHAR(100), device_model VARCHAR(100), severity VARCHAR(20), file_size_bytes BIGINT, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE compliance_baselines (id SERIAL PRIMARY KEY, name VARCHAR(200) NOT NULL, description TEXT, template_type VARCHAR(50), created_by VARCHAR(100), created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE compliance_results (id SERIAL PRIMARY KEY, baseline_id INTEGER REFERENCES compliance_baselines(id), device_id INTEGER REFERENCES devices(id), compliance_status VARCHAR(20) NOT NULL, drift_count INTEGER DEFAULT 0, details JSONB, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE users (id SERIAL PRIMARY KEY, username VARCHAR(100) NOT NULL UNIQUE, email VARCHAR(200), full_name VARCHAR(200), role VARCHAR(50) NOT NULL, is_active BOOLEAN DEFAULT true, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE job_history (id SERIAL PRIMARY KEY, job_name VARCHAR(200) NOT NULL, job_type VARCHAR(100) NOT NULL, status VARCHAR(50) NOT NULL, target_count INTEGER DEFAULT 0, success_count INTEGER DEFAULT 0, failure_count INTEGER DEFAULT 0, started_at TIMESTAMP, completed_at TIMESTAMP, created_by VARCHAR(100), created_at TIMESTAMP DEFAULT NOW());

INSERT INTO device_types (name,category,protocol) VALUES ('PowerEdge R750','Compute','Redfish'),('PowerEdge R760','Compute','Redfish'),('PowerEdge MX740c','Compute','Redfish'),('PowerEdge R650','Compute','Redfish'),('PowerSwitch S5248','Network','SNMP'),('PowerSwitch N3248','Network','SNMP'),('PowerStore 500T','Storage','Redfish'),('PowerStore 1200T','Storage','Redfish'),('MX7000 Chassis','Chassis','Redfish'),('VxRail E560','Converged','Redfish');
INSERT INTO devices (service_tag,device_name,device_type_id,model,ip_address,firmware_version,health_status,ome_device_id) SELECT 'SVC'||LPAD(i::TEXT,7,'0'),'srv-'||LPAD(i::TEXT,4,'0')||'.dc.local', CASE WHEN i<=200 THEN 1 WHEN i<=350 THEN 2 WHEN i<=400 THEN 3 WHEN i<=430 THEN 5 WHEN i<=460 THEN 7 WHEN i<=480 THEN 9 ELSE 4 END, CASE WHEN i<=200 THEN 'PowerEdge R750' WHEN i<=350 THEN 'PowerEdge R760' WHEN i<=400 THEN 'PowerEdge MX740c' WHEN i<=430 THEN 'PowerSwitch S5248' WHEN i<=460 THEN 'PowerStore 500T' WHEN i<=480 THEN 'MX7000 Chassis' ELSE 'PowerEdge R650' END, ('10.'||((i/256)+1)||'.'||(i%256)||'.'||((i*7)%254+1))::INET, (1+(i%5))||'.'||((i*3)%10)||'.'||((i*7)%100), CASE (i%20) WHEN 0 THEN 'Critical' WHEN 1 THEN 'Warning' ELSE 'OK' END, 10000+i FROM generate_series(1,500) AS i;
INSERT INTO device_inventory (device_id,component_type,component_name,manufacturer,model,serial_number,capacity,status) SELECT d.id,c.ct,c.cn,c.mf,c.md,'SN'||d.id||'-'||c.s,c.cap,CASE WHEN random()<0.05 THEN 'Warning' ELSE 'OK' END FROM devices d CROSS JOIN (VALUES ('CPU','Xeon Gold 6338','Intel','6338','128 Cores',0),('Memory','DDR4 64GB','Samsung','M393A8G40','64 GB',1),('Storage','NVMe 1.92TB','Samsung','PM9A3','1.92 TB',2),('NIC','25GbE','Broadcom','BCM57414','25 GbE',3),('PSU','1400W PSU','Dell','E1400','1400 W',4),('Fan','System Fan','Dell','StdFan','N/A',5)) AS c(ct,cn,mf,md,cap,s) WHERE d.id<=500;
INSERT INTO groups (name,description,parent_group_id,group_type,created_by) VALUES ('All Devices','Root',NULL,'Static','admin'),('Production','Prod servers',1,'Static','admin'),('Development','Dev servers',1,'Static','admin'),('Network','Switches',1,'Static','admin'),('Storage','Arrays',1,'Static','admin'),('Chassis','Enclosures',1,'Static','admin'),('DC-East A1','Rack A1',2,'Static','admin'),('DC-East A2','Rack A2',2,'Static','admin'),('DC-West B1','Rack B1',2,'Static','admin'),('Health Critical','Critical',NULL,'Dynamic','admin');
INSERT INTO group_memberships (group_id,device_id) SELECT 2,id FROM devices WHERE id<=150;
INSERT INTO group_memberships (group_id,device_id) SELECT 3,id FROM devices WHERE id>150 AND id<=300;
INSERT INTO group_memberships (group_id,device_id) SELECT 4,id FROM devices WHERE model LIKE 'PowerSwitch%';
INSERT INTO group_memberships (group_id,device_id) SELECT 5,id FROM devices WHERE model LIKE 'PowerStore%';
INSERT INTO group_memberships (group_id,device_id) SELECT 10,id FROM devices WHERE health_status='Critical';
INSERT INTO alert_categories (name,subcategories) VALUES ('System Health','["PSU","Memory","CPU","Temp","Fan"]'),('Storage','["Disk","RAID","Controller"]'),('Configuration','["BIOS","iDRAC","Network"]'),('Audit','["Login","Logout","UserChange"]'),('Updates','["FirmwareApplied","FirmwareFailed"]');
INSERT INTO alerts (device_id,alert_category_id,severity,message,message_id,source,subcategory,acknowledged,alert_time) SELECT (random()*499+1)::INT,(random()*4+1)::INT, CASE (i%10) WHEN 0 THEN 'Critical' WHEN 1 THEN 'Critical' WHEN 2 THEN 'Warning' WHEN 3 THEN 'Warning' ELSE 'Info' END, CASE (i%6) WHEN 0 THEN 'PSU redundancy lost' WHEN 1 THEN 'Memory ECC error' WHEN 2 THEN 'CPU temp high' WHEN 3 THEN 'Disk predictive failure' WHEN 4 THEN 'Fan below threshold' ELSE 'Link down' END, 'MSG-'||LPAD((i%500)::TEXT,5,'0'), CASE (i%3) WHEN 0 THEN 'iDRAC' WHEN 1 THEN 'BIOS' ELSE 'CPLD' END, CASE (i%5) WHEN 0 THEN 'PSU' WHEN 1 THEN 'Memory' WHEN 2 THEN 'CPU' WHEN 3 THEN 'Disk' ELSE 'Fan' END, random()<0.3, NOW()-(random()*INTERVAL '30 days') FROM generate_series(1,2000) AS i;
INSERT INTO device_health (device_id,overall_health,cpu_health,memory_health,storage_health,power_health,cpu_usage_percent,memory_usage_percent,system_temp_celsius,power_consumed_watts) SELECT id,health_status,'OK','OK','OK','OK',(random()*80+10)::NUMERIC(5,2),(random()*60+20)::NUMERIC(5,2),(random()*25+22)::NUMERIC(5,1),(random()*500+100)::INT FROM devices;
INSERT INTO firmware_catalog (name,version,component_type,device_model,severity,file_size_bytes) SELECT 'Dell '||c||' Update',v||'.'||i,c,m, CASE (i%3) WHEN 0 THEN 'Critical' WHEN 1 THEN 'Recommended' ELSE 'Optional' END,(random()*500000000+1000000)::BIGINT FROM (VALUES('iDRAC','R750','6'),('iDRAC','R760','7'),('BIOS','R750','2'),('BIOS','R760','2'),('NIC','R750','22'),('RAID','R760','4')) AS fw(c,m,v) CROSS JOIN generate_series(1,3) AS i;
INSERT INTO compliance_baselines (name,description,template_type,created_by) VALUES ('Prod BIOS Standard','Production BIOS','BIOS','admin'),('Security Hardening','iDRAC security','iDRAC','admin'),('Network Std','NIC settings','Network','admin');
INSERT INTO compliance_results (baseline_id,device_id,compliance_status,drift_count,details) SELECT (i%3)+1,(i%400)+1,CASE (i%5) WHEN 0 THEN 'NonCompliant' ELSE 'Compliant' END, CASE WHEN i%5=0 THEN (random()*5+1)::INT ELSE 0 END, '{}'::JSONB FROM generate_series(1,600) AS i;
INSERT INTO users (username,email,full_name,role) VALUES ('admin','admin@corp.local','Admin','Administrator'),('jsmith','js@corp.local','John Smith','DeviceManager'),('mj','mj@corp.local','Muralidhar J','Administrator'),('venkat','vd@corp.local','Venkat D','Administrator'),('viewer','v@corp.local','Viewer','Viewer');
INSERT INTO job_history (job_name,job_type,status,target_count,success_count,failure_count,started_at,completed_at,created_by) SELECT CASE (i%5) WHEN 0 THEN 'Discovery' WHEN 1 THEN 'Inventory' WHEN 2 THEN 'HealthCheck' WHEN 3 THEN 'FirmwareUpdate' ELSE 'ComplianceCheck' END||'-'||i, CASE (i%5) WHEN 0 THEN 'Discovery' WHEN 1 THEN 'Inventory' WHEN 2 THEN 'HealthCheck' WHEN 3 THEN 'FirmwareUpdate' ELSE 'ComplianceCheck' END, CASE (i%8) WHEN 0 THEN 'Failed' ELSE 'Completed' END, (random()*200+10)::INT,(random()*200)::INT,(random()*5)::INT, NOW()-(i*4||' hours')::INTERVAL, NOW()-((i*4-1)||' hours')::INTERVAL, CASE (i%3) WHEN 0 THEN 'admin' WHEN 1 THEN 'jsmith' ELSE 'mj' END FROM generate_series(1,100) AS i;

-- captures ALL tables:
CREATE PUBLICATION dbz_publication FOR ALL TABLES;

-- Do this (only specific tables):
-- CREATE PUBLICATION dbz_publication FOR TABLE devices, alerts, device_health, groups, ...;